# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: pygments

kramdown:
  input: GFM

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : Siglo XIX - XX
tagline: Site Tagline
icon: /img/logo.png
logo: /img/logo-l.png
author :
  name : Tomas Achi - Carlos Echandi - Stefano Gerli - Alexander Wu
copyright: © iGerli 2015
